# -*- coding: utf-8 -*-
"""casa32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_bIv5UcdExuS4F2tfAwcR65XSQbvAnDw
"""

from sklearn.metrics import r2_score , mean_squared_error
from sklearn.model_selection import train_test_split , cross_val_score , cross_val_predict , GridSearchCV
from sklearn.linear_model import LinearRegression , Ridge
from sklearn.preprocessing import PolynomialFeatures , StandardScaler

import pandas as pd
import numpy as np
import seaborn as sns
import requests
import matplotlib.pyplot as plt

df = pd.read_csv("kc_house_data_NaN.csv")
df.head()

def limpia_datos(name_column):
    avg = df[name_column].astype('float').mean(axis = 0)
    df[name_column].replace(np.nan , avg , inplace=True)
    print(f'El valor promedio es {avg} de la columna {name_column} ')

limpia_datos('sqft_living')
limpia_datos('grade')
limpia_datos('bathrooms')

df.columns

y_data  = df['price']
x_data = df.drop(columns='price' , inplace=True)

"""## Regrecion Lineal Simple"""

'''
### modelo regrecion simple
lr = LinearRegression()
y_data1  = y_data
x_data1 = df[["sqft_living"]]

lr.fit(x_data1 , y_data1)
lr.predict(x_data1)

print(f"La intercession es de {lr.intercept_}")
print(f"Los coeficientes son {lr.coef_}")

##datos predichos
yhat1 = lr.predict(x_data1)

import matplotlib.pyplot as plt

# Datos reales
plt.scatter(x_data1, y_data1, label="Datos reales" )

# Línea de regresión
plt.plot(x_data1, yhat1, label="Línea de regresión")

# Etiquetas
plt.xlabel("sqft_living")
plt.ylabel("Precio")
plt.title("Regresión Lineal Simple")

# Leyenda
plt.legend()


plt.show()

"""## Regrecion Lineal Multiple

"""
'''

### modelo regrecion simple
lr = LinearRegression()
y_data2  = y_data
x_data2 = df[['sqft_living', 'grade', 'bathrooms']]

lr.fit(x_data2 , y_data2)
lr.predict(x_data2)

print(f"La intercession es de {lr.intercept_}")
print(f"Los coeficientes son {lr.coef_}")

##datos predichos
yhat2 = lr.predict(x_data2)

print(f"El coeficiente de error es de : {r2_score(y_data2  , yhat2 )}")
print(f"El coeficiente de error es de : {mean_squared_error(y_data2  , yhat2 )}")

"""## Regrecion Lineal Polinmica

"""

# Variables
x_data3 = df[['sqft_living', 'grade', 'bathrooms']]
y_data3 = y_data

'''
# Transformación polinómica
pr = PolynomialFeatures(degree=3)
X_poly = pr.fit_transform(x_data3)

'''
# Modelo
lr = LinearRegression()
lr.fit(X_poly, y_data3)



# Predicciones
yhat3 = lr.predict(X_poly)


print(f"El coeficiente de error es de : {r2_score(y_data3  , yhat3 )}")
print(f"El MSE de error es de : {mean_squared_error(y_data3  , yhat3 )}")

